import { addDays, subDays, subHours, subMonths } from 'date-fns';
import type { Ticket } from '@/types';

const now = new Date();

export const tickets: Ticket[] = [
  {
    ticket_id: 'TKT-86431',
    employee_id: 'EMP-001',
    employee_name: 'Alice Johnson',
    avatar: 'https://picsum.photos/seed/1/40/40',
    category: 'Hardware',
    description: 'Laptop screen is flickering.',
    status: 'In Progress',
    created_at: subHours(now, 4).toISOString(),
    updated_at: subHours(now, 1).toISOString(),
    priority: 'High',
  },
  {
    ticket_id: 'TKT-48295',
    employee_id: 'EMP-002',
    employee_name: 'Bob Williams',
    avatar: 'https://picsum.photos/seed/2/40/40',
    category: 'Software',
    description: 'Unable to install new design software, license key not working.',
    status: 'Pending',
    created_at: subDays(now, 1).toISOString(),
    updated_at: subHours(now, 2).toISOString(),
    priority: 'Medium',
  },
  {
    ticket_id: 'TKT-50912',
    employee_id: 'EMP-003',
    employee_name: 'Charlie Brown',
    avatar: 'https://picsum.photos/seed/3/40/40',
    category: 'Network',
    description: 'Cannot connect to the office Wi-Fi.',
    status: 'Resolved',
    created_at: subDays(now, 2).toISOString(),
    updated_at: subDays(now, 1).toISOString(),
    priority: 'High',
  },
  {
    ticket_id: 'TKT-73246',
    employee_id: 'EMP-004',
    employee_name: 'Diana Prince',
    avatar: 'https://picsum.photos/seed/4/40/40',
    category: 'Account',
    description: 'Password reset required for email account.',
    status: 'Resolved',
    created_at: subDays(now, 3).toISOString(),
    updated_at: subDays(now, 3).toISOString(),
    priority: 'Low',
  },
  {
    ticket_id: 'TKT-19875',
    employee_id: 'EMP-005',
    employee_name: 'Ethan Hunt',
    avatar: 'https://picsum.photos/seed/5/40/40',
    category: 'Hardware',
    description: 'Docking station not recognizing external monitors.',
    status: 'In Progress',
    created_at: subHours(now, 8).toISOString(),
    updated_at: subHours(now, 1).toISOString(),
    priority: 'Medium',
  },
  {
    ticket_id: 'TKT-62453',
    employee_id: 'EMP-006',
    employee_name: 'Fiona Glenanne',
    avatar: 'https://picsum.photos/seed/6/40/40',
    category: 'Software',
    description: 'VPN client disconnects frequently.',
    status: 'Pending',
    created_at: subDays(now, 5).toISOString(),
    updated_at: subDays(now, 2).toISOString(),
    priority: 'High',
  },
  {
    ticket_id: 'TKT-31415',
    employee_id: 'EMP-007',
    employee_name: 'George Costanza',
    avatar: 'https://picsum.photos/seed/7/40/40',
    category: 'Hardware',
    description: 'My ergonomic keyboard has stopped working suddenly.',
    status: 'Pending',
    created_at: subDays(now, 1).toISOString(),
    updated_at: subDays(now, 1).toISOString(),
    priority: 'Medium',
  },
  {
    ticket_id: 'TKT-27182',
    employee_id: 'EMP-008',
    employee_name: 'Hannah Montana',
    avatar: 'https://picsum.photos/seed/8/40/40',
    category: 'Network',
    description: 'Slow internet speed across the whole floor.',
    status: 'In Progress',
    created_at: subHours(now, 2).toISOString(),
    updated_at: subHours(now, 1).toISOString(),
    priority: 'High',
  },
  {
    ticket_id: 'TKT-16180',
    employee_id: 'EMP-009',
    employee_name: 'Indiana Jones',
    avatar: 'https://picsum.photos/seed/9/40/40',
    category: 'Account',
    description: 'Locked out of the internal portal after too many failed attempts.',
    status: 'Resolved',
    created_at: subDays(now, 7).toISOString(),
    updated_at: subDays(now, 7).toISOString(),
    priority: 'Medium',
  },
  {
    ticket_id: 'TKT-11235',
    employee_id: 'EMP-010',
    employee_name: 'Jack Sparrow',
    avatar: 'https://picsum.photos/seed/10/40/40',
    category: 'Software',
    description: "Spreadsheet software crashes when opening large files.",
    status: 'In Progress',
    created_at: subDays(now, 4).toISOString(),
    updated_at: subDays(now, 1).toISOString(),
    priority: 'Medium',
  },
  {
    ticket_id: 'TKT-10110',
    employee_id: 'EMP-011',
    employee_name: 'Kara Thrace',
    avatar: 'https://picsum.photos/seed/11/40/40',
    category: 'Hardware',
    description: 'Company-issued phone battery drains extremely quickly.',
    status: 'Pending',
    created_at: subMonths(subDays(now, 1), 1).toISOString(),
    updated_at: subMonths(subDays(now, 1), 1).toISOString(),
    priority: 'Low',
  },
    {
    ticket_id: 'TKT-10111',
    employee_id: 'EMP-012',
    employee_name: 'Laura Roslin',
    avatar: 'https://picsum.photos/seed/12/40/40',
    category: 'Software',
    description: 'Cannot access shared drive folder for project files.',
    status: 'Resolved',
    created_at: subMonths(now, 2).toISOString(),
    updated_at: subMonths(now, 2).toISOString(),
    priority: 'High',
  },
  {
    ticket_id: 'TKT-10112',
    employee_id: 'EMP-013',
    employee_name: 'Michael Scott',
    avatar: 'https://picsum.photos/seed/13/40/40',
    category: 'Hardware',
    description: 'The printer on the second floor is jammed again.',
    status: 'Resolved',
    created_at: subMonths(now, 2).toISOString(),
    updated_at: subMonths(now, 1).toISOString(),
    priority: 'Low',
  },
   {
    ticket_id: 'TKT-10113',
    employee_id: 'EMP-014',
    employee_name: 'Neo',
    avatar: 'https://picsum.photos/seed/14/40/40',
    category: 'Network',
    description: 'Experiencing high latency when connected to the corporate network from home.',
    status: 'In Progress',
    created_at: subMonths(now, 3).toISOString(),
    updated_at: subMonths(now, 1).toISOString(),
    priority: 'High',
  },
];
